import {
  HomeOutlined,
  ProjectOutlined,
  ShoppingCartOutlined,
  BarsOutlined,
  BookOutlined,
  GlobalOutlined,
  UsergroupDeleteOutlined,
} from "@ant-design/icons"

export const sidebarData = [
  {
    id: 1,
    title: "Reviews",
    icon: HomeOutlined,
    path: "/reviews",
    active: "",
    link: [],
  },
  {
    id: 2,
    title: "News",
    icon: UsergroupDeleteOutlined,
    path: "/news",
    active: "",
    link: [],
  },
  {
    id: 4,
    title: "category",
    icon: ProjectOutlined,
    path: "/category",
    active: "",
    link: [],
  },
  {
    id: 5,
    title: "orders",
    icon: ProjectOutlined,
    path: "/orders",
    active: "",
    link: [],
  },

  {
    id: 6,
    title: "Auth",
    icon: BookOutlined,
    path: "/auth",
    active: "",
    link: [],
  },
  {
    id: 7,
    title: "Brands",
    icon: ProjectOutlined,
    path: "/brands",
    active: "",
    link: [],
  },
  {
    id: 8,
    title: "products",
    icon: ShoppingCartOutlined,
    path: "/products",
    active: "",
    link: [],
  },
  {
    id: 10,
    title: "events",
    icon: GlobalOutlined,
    path: "/events",
    active: "",
    link: [],
  },
  {
    id: 11,
    title: "attributes",
    icon: BarsOutlined,
    path: "/attributes",
    active: "",
    link: [],
  },
  {
    id: 12,
    title: "pages",
    icon: ShoppingCartOutlined,
    path: "/pages",
    active: "",
    link: [],
  },
]
